# Introduction to Pandas
## What is Pandas?
A powerful library for data manipulation and analysis in Python.
Built on top of NumPy, provides data structures like Series and DataFrame.
## Why use Pandas?
* Easy data cleaning and transformation.
* Efficient handling of large datasets.
* Integration with other Python libraries like Matplotlib and Seaborn for visualization.

In [30]:
# !pip install pandas
import pandas as pd

In [ ]:

data = {
    'Name': ['Nishit', 'Palak', 'Rohan'],
    'Age': [21, 22, 29],
    'Department': ['IT', 'HR', 'Finance']
}
print(type(data))
df = pd.DataFrame(data)
print(type(df))
print(df)

print(df['Name'])

# Employees with Age > 21 
print(df[df['Age'] > 21])

df['Salary'] = [50000, 60000, 55000]
print(df)

# Increase salary by 10%
df['New_Salary'] = df['Salary'].apply(lambda x: x * 1.1)
print(df)

# Average salary by Department
grouped = df.groupby('Department')['Salary'].mean()
print(grouped)


data1 = {
    'Name': ['Nishit', 'Palak', 'Rohan', 'Sneha', 'Amit'],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'Salary': [50000, 60000, 55000, 65000, 62000]
}

df = pd.DataFrame(data1)
print(df['Department'].value_counts())

avg_salary = df.groupby('Department')['Salary'].mean()
print(print("Average Salary per Department:\n", avg_salary)
)

# Group by Department and find max salary
max_salary_per_dept = df.groupby('Department')['Salary'].transform('max')

# Filter employees with salary equal to max salary in their department
top_earners = df[df['Salary'] == max_salary_per_dept]
print("\nTop Earners per Department:\n", top_earners)

In [31]:
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [32]:
df = pd.DataFrame([[1,2.0,3],[4,5,6],[7,8,9]], columns=['A','B','C'], index=['x','y','z'])

In [33]:
df.tail(2)

   A    B  C
y  4  5.0  6
z  7  8.0  9

In [34]:
df.head(1)

   A    B  C
x  1  2.0  3

In [35]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [36]:
df.index

Index(['x', 'y', 'z'], dtype='object')

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      float64
 2   C       3 non-null      int64
dtypes: float64(1), int64(2)
memory usage: 96.0+ bytes

In [44]:
print(df.describe())
print(df)

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0
   A    B  C
x  1  2.0  3
y  4  5.0  6
z  7  8.0  9

In [46]:
df['A'].unique()

array([1, 4, 7])

In [48]:
df.shape

(3, 3)

In [49]:
df.size

9